In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [2]:
cv =CountVectorizer(max_features=5000, stop_words="english")

In [18]:
df = pd.read_csv("/Users/sushank/Documents/Data_analysis/movie-prediction/data/processed/final_features_with_tags.csv")
df

,id,title,tags
0,19995,Avatar,action adventure fantasy sciencefiction cultur...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...
2,206647,Spectre,action adventure crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,action crime drama thriller dccomics crimefigh...
4,49529,John Carter,action adventure sciencefiction basedonnovel m...
...,...,...,...
3960,124606,Bang,drama gang audition policefake homeless actres...
3961,14337,Primer,sciencefiction drama thriller distrust garage ...
3962,9367,El Mariachi,action crime thriller unitedstates–mexicobarri...
3963,72766,Newlyweds,comedy romance a newlywed couple's honeymoon i...
3964,126186,Shanghai Calling,a new yorker in shanghai when ambitious new yo...

In [4]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [5]:
def stem(obj):
    y = [] 
    for i in obj.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [6]:
df['tags'] = df['tags'].apply(stem)

In [19]:
vectors = cv.fit_transform(df["tags"]).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3965, 5000))

In [8]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [9]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(vectors)[0] #har movie ka har movie k sath cosine dist( angle )

array([1.        , 0.11785113, 0.0766965 , ..., 0.01656347, 0.02721655,
       0.        ], shape=(3965,))

In [10]:
df[df["title"] == "Avatar"].index[0]

0

In [11]:
similarity_mat = cosine_similarity(vectors)

In [12]:
list(enumerate(similarity_mat[0]))
#index with similarty usefull for sorting

[(0, np.float64(1.0)),
 (1, np.float64(0.11785113019775792)),
 (2, np.float64(0.07669649888473704)),
 (3, np.float64(0.06666666666666667)),
 (4, np.float64(0.21295885499997996)),
 (5, np.float64(0.11952286093343938)),
 (6, np.float64(0.05423261445466405)),
 (7, np.float64(0.12909944487358058)),
 (8, np.float64(0.05039526306789696)),
 (9, np.float64(0.10647942749999)),
 (10, np.float64(0.08190601557786016)),
 (11, np.float64(0.07784989441615231)),
 (12, np.float64(0.04020151261036849)),
 (13, np.float64(0.13333333333333333)),
 (14, np.float64(0.05423261445466405)),
 (15, np.float64(0.0967301666813349)),
 (16, np.float64(0.12472191289246472)),
 (17, np.float64(0.08439494725697222)),
 (18, np.float64(0.06708728072355036)),
 (19, np.float64(0.05291171934216968)),
 (20, np.float64(0.11785113019775792)),
 (21, np.float64(0.0535479552601666)),
 (22, np.float64(0.10540925533894598)),
 (23, np.float64(0.07161148740394328)),
 (24, np.float64(0.046880723093849545)),
 (25, np.float64(0.16101529717988267)),
 (26, np.float64(0.20339007194925077)),
 (27, np.float64(0.12253577034896797)),
 (28, np.float64(0.07968190728895959)),
 (29, np.float64(0.060858061945018464)),
 (30, np.float64(0.16609095970747995)),
 (31, np.float64(0.09390602830316849)),
 (32, np.float64(0.08770580193070293)),
 (33, np.float64(0.0)),
 (34, np.float64(0.08770580193070293)),
 (35, np.float64(0.1538554437923503)),
 (36, np.float64(0.06900655593423542)),
 (37, np.float64(0.07339758434175737)),
 (38, np.float64(0.0954819832052577)),
 (39, np.float64(0.09312403943594377)),
 (40, np.float64(0.14611900125320157)),
 (41, np.float64(0.0)),
 (42, np.float64(0.10143010324169743)),
 (43, np.float64(0.02923526731023431)),
 (44, np.float64(0.1118033988749895)),
 (45, np.float64(0.11236664374387369)),
 (46, np.float64(0.2138089935299395)),
 (47, np.float64(0.11009637651263605)),
 (48, np.float64(0.07352146220938079)),
 (49, np.float64(0.1511857892036909)),
 (50, np.float64(0.07178425360775541)),
 (51, np.float64(0.12909944487358058)),
 (52, np.float64(0.05976143046671969)),
 (53, np.float64(0.05443310539518174)),
 (54, np.float64(0.06429904295605494)),
 (55, np.float64(0.042591770999996)),
 (56, np.float64(0.061429511683395124)),
 (57, np.float64(0.11666666666666667)),
 (58, np.float64(0.017099639201419235)),
 (59, np.float64(0.2086996778999804)),
 (60, np.float64(0.07231015260621873)),
 (61, np.float64(0.06931669932133819)),
 (62, np.float64(0.07905694150420949)),
 (63, np.float64(0.01769149641447584)),
 (64, np.float64(0.1840174824912945)),
 (65, np.float64(0.10379985922153641)),
 (66, np.float64(0.023718935565494)),
 (67, np.float64(0.06984302957695783)),
 (68, np.float64(0.08791739645277159)),
 (69, np.float64(0.12091270835166862)),
 (70, np.float64(0.02817180849095055)),
 (71, np.float64(0.17770466332772772)),
 (72, np.float64(0.11366572324507891)),
 (73, np.float64(0.085183541999992)),
 (74, np.float64(0.012926112238824687)),
 (75, np.float64(0.07178425360775541)),
 (76, np.float64(0.045407660918649985)),
 (77, np.float64(0.09817613873476319)),
 (78, np.float64(0.06741998624632421)),
 (79, np.float64(0.15525933593055521)),
 (80, np.float64(0.10540925533894599)),
 (81, np.float64(0.13349824784699546)),
 (82, np.float64(0.07897985036787898)),
 (83, np.float64(0.12253577034896797)),
 (84, np.float64(0.07905694150420949)),
 (85, np.float64(0.0627702980962258)),
 (86, np.float64(0.05039526306789696)),
 (87, np.float64(0.17155007848855516)),
 (88, np.float64(0.09245003270420486)),
 (89, np.float64(0.06324555320336758)),
 (90, np.float64(0.16609095970747995)),
 (91, np.float64(0.11744404390294069)),
 (92, np.float64(0.06741998624632421)),
 (93, np.float64(0.0834965721446866)),
 (94, np.float64(0.06523280730534423)),
 (95, np.float64(0.023281009858985943)),
 (96, np.float64(0.05847053462046862)),
 (97, np.float64(0.1098967455659645)),
 (98, np.float64(0.11180339887498948)),
 (99, np.float64(0.07231015260621873)),
 (100, np.float64(0.051899929610768204)),
 (101, np.float64(0.0894427190999916)),
 (102, np.float64(0.05590169943749475)),
 (103, np.float64(0.05345224838248488)),
 (104, np.float64(0.14757295747452437)),
 (105, np.float64(0.06984302957695783)),
 (106, np.float64(0.037267799624996496)),
 (107, np.float64(0.1591320125431105)),
 (108, np.float64(0.09200874124564723)),
 (109, np.float64(0.04020151261036849)),
 (110, np.float64(0.04020151261036849)),
 (111, np.float64(0.0563436169819011)),
 (112, np.float64(0.060858061945018464)),
 (113, np.float64(0.10226199851298272)),
 (114, np.float64(0.05933255459866465)),
 (115, np.float64(0.038173222287591214)),
 (116, np.float64(0.0)),
 (117, np.float64(0.12422599874998831)),
 (118, np.float64(0.10379985922153641)),
 (119, np.float64(0.09390602830316849)),
 (120, np.float64(0.054635836470815304)),
 (121, np.float64(0.07093269021319087)),
 (122, np.float64(0.11501092655705904)),
 (123, np.float64(0.14815943949743846)),
 (124, np.float64(0.09466030570784414)),
 (125, np.float64(0.02387049580131443)),
 (126, np.float64(0.1538554437923503)),
 (127, np.float64(0.060858061945018464)),
 (128, np.float64(0.04836508334066745)),
 (129, np.float64(0.10886621079036347)),
 (130, np.float64(0.025949964805384102)),
 (131, np.float64(0.020286020648339488)),
 (132, np.float64(0.02923526731023431)),
 (133, np.float64(0.13968605915391566)),
 (134, np.float64(0.11969747440993463)),
 (135, np.float64(0.04020151261036849)),
 (136, np.float64(0.09428090415820634)),
 (137, np.float64(0.07784989441615231)),
 (138, np.float64(0.09622504486493762)),
 (139, np.float64(0.042591770999996)),
 (140, np.float64(0.01769149641447584)),
 (141, np.float64(0.013900960937138319)),
 (142, np.float64(0.05113099925649136)),
 (143, np.float64(0.08304547985373997)),
 (144, np.float64(0.13503191561115555)),
 (145, np.float64(0.14638501094228)),
 (146, np.float64(0.17888543819998318)),
 (147, np.float64(0.07559289460184544)),
 (148, np.float64(0.07076598565790336)),
 (149, np.float64(0.10886621079036347)),
 (150, np.float64(0.018211945490271768)),
 (151, np.float64(0.05198752449100364)),
 (152, np.float64(0.08770580193070293)),
 (153, np.float64(0.13585191893923582)),
 (154, np.float64(0.051899929610768204)),
 (155, np.float64(0.12046772038736685)),
 (156, np.float64(0.05536365323582665)),
 (157, np.float64(0.05847053462046862)),
 (158, np.float64(0.044444444444444446)),
 (159, np.float64(0.08989331499509895)),
 (160, np.float64(0.041344911529736156)),
 (161, np.float64(0.09938079899999065)),
 (162, np.float64(0.15220988371246985)),
 (163, np.float64(0.13701805122009747)),
 (164, np.float64(0.13146843962443588)),
 (165, np.float64(0.019920476822239897)),
 (166, np.float64(0.1788854381999832)),
 (167, np.float64(0.0417482860723433)),
 (168, np.float64(0.09093257859606313)),
 (169, np.float64(0.08040302522073697)),
 (170, np.float64(0.02519763153394848)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0219793491131929)),
 (173, np.float64(0.09128709291752769)),
 (174, np.float64(0.02047650389446504)),
 (175, np.float64(0.03948992518393949)),
 (176, np.float64(0.12171612389003691)),
 (177, np.float64(0.06320606175199697)),
 (178, np.float64(0.1818651571921263)),
 (179, np.float64(0.046004370622823615)),
 (180, np.float64(0.050964719143762556)),
 (181, np.float64(0.1318760946791574)),
 (182, np.float64(0.02047650389446504)),
 (183, np.float64(0.12433397443204185)),
 (184, np.float64(0.12384047490133089)),
 (185, np.float64(0.04348853820356281)),
 (186, np.float64(0.06030226891555273)),
 (187, np.float64(0.07011719365194521)),
 (188, np.float64(0.0)),
 (189, np.float64(0.05039526306789696)),
 (190, np.float64(0.04348853820356281)),
 (191, np.float64(0.03312693299999688)),
 (192, np.float64(0.07559289460184544)),
 (193, np.float64(0.07572824456627532)),
 (194, np.float64(0.09325048082403138)),
 (195, np.float64(0.0)),
 (196, np.float64(0.0267739776300833)),
 (197, np.float64(0.07161148740394328)),
 (198, np.float64(0.044946657497549475)),
 (199, np.float64(0.06506000486323556)),
 (200, np.float64(0.11523511960911878)),
 (201, np.float64(0.06324555320336758)),
 (202, np.float64(0.1107273064716533)),
 (203, np.float64(0.0596284793999944)),
 (204, np.float64(0.0659380473395787)),
 (205, np.float64(0.021744269101781406)),
 (206, np.float64(0.08040302522073697)),
 (207, np.float64(0.05383819020581655)),
 (208, np.float64(0.0)),
 (209, np.float64(0.057735026918962574)),
 (210, np.float64(0.0563436169819011)),
 (211, np.float64(0.08040302522073697)),
 (212, np.float64(0.03253000243161778)),
 (213, np.float64(0.07784989441615231)),
 (214, np.float64(0.14907119849998599)),
 (215, np.float64(0.041344911529736156)),
 (216, np.float64(0.07231015260621873)),
 (217, np.float64(0.08888888888888889)),
 (218, np.float64(0.07231015260621873)),
 (219, np.float64(0.042591770999996)),
 (220, np.float64(0.026352313834736494)),
 (221, np.float64(0.06900655593423542)),
 (222, np.float64(0.09872481295984872)),
 (223, np.float64(0.1025978352085154)),
 (224, np.float64(0.08231079972079913)),
 (225, np.float64(0.05923488777590924)),
 (226, np.float64(0.10079052613579392)),
 (227, np.float64(0.06666666666666667)),
 (228, np.float64(0.11644450194791642)),
 (229, np.float64(0.11640504929492972)),
 (230, np.float64(0.051899929610768204)),
 (231, np.float64(0.09817613873476319)),
 (232, np.float64(0.08333333333333333)),
 (233, np.float64(0.04303314829119353)),
 (234, np.float64(0.0954819832052577)),
 (235, np.float64(0.07254762501100118)),
 (236, np.float64(0.07968190728895959)),
 (237, np.float64(0.07352146220938079)),
 (238, np.float64(0.09200874124564723)),
 (239, np.float64(0.06839855680567694)),
 (240, np.float64(0.0)),
 (241, np.float64(0.040572041296678976)),
 (242, np.float64(0.11925695879998881)),
 (243, np.float64(0.0)),
 (244, np.float64(0.036155076303109365)),
 (245, np.float64(0.03669879217087869)),
 (246, np.float64(0.056796183424706485)),
 (247, np.float64(0.07829602926862712)),
 (248, np.float64(0.0)),
 (249, np.float64(0.149071198499986)),
 (250, np.float64(0.04714045207910317)),
 (251, np.float64(0.03214952147802747)),
 (252, np.float64(0.0535479552601666)),
 (253, np.float64(0.17638342073763938)),
 (254, np.float64(0.021081851067789197)),
 (255, np.float64(0.09245003270420486)),
 (256, np.float64(0.08606629658238704)),
 (257, np.float64(0.0)),
 (258, np.float64(0.023570226039551584)),
 (259, np.float64(0.08606629658238706)),
 (260, np.float64(0.05443310539518174)),
 (261, np.float64(0.04216370213557839)),
 (262, np.float64(0.02387049580131443)),
 (263, np.float64(0.07968190728895959)),
 (264, np.float64(0.06324555320336758)),
 (265, np.float64(0.024507154069793594)),
 (266, np.float64(0.01893206114156883)),
 (267, np.float64(0.08074832969069799)),
 (268, np.float64(0.1297498240269205)),
 (269, np.float64(0.0573775310549247)),
 (270, np.float64(0.07728981596002804)),
 (271, np.float64(0.12403473458920847)),
 (272, np.float64(0.0834965721446866)),
 (273, np.float64(0.0)),
 (274, np.float64(0.058722021951470346)),
 (275, np.float64(0.03914801463431356)),
 (276, np.float64(0.02387049580131443)),
 (277, np.float64(0.0163626897891272)),
 (278, np.float64(0.017099639201419235)),
 (279, np.float64(0.081813448945636)),
 (280, np.float64(0.023002185311411807)),
 (281, np.float64(0.04303314829119353)),
 (282, np.float64(0.0563436169819011)),
 (283, np.float64(0.06388765649999399)),
 (284, np.float64(0.07161148740394328)),
 (285, np.float64(0.02721655269759087)),
 (286, np.float64(0.17155007848855516)),
 (287, np.float64(0.09093257859606313)),
 (288, np.float64(0.05345224838248488)),
 (289, np.float64(0.04095300778893008)),
 (290, np.float64(0.021295885499998)),
 (291, np.float64(0.05383819020581655)),
 (292, np.float64(0.14611900125320154)),
 (293, np.float64(0.08549819600709617)),
 (294, np.float64(0.07968190728895959)),
 (295, np.float64(0.024845199749997663)),
 (296, np.float64(0.06880209161537815)),
 (297, np.float64(0.17177950029416045)),
 (298, np.float64(0.09312403943594377)),
 (299, np.float64(0.10043247695396126)),
 (300, np.float64(0.05847053462046862)),
 (301, np.float64(0.0573775310549247)),
 (302, np.float64(0.02666666666666667)),
 (303, np.float64(0.16865480854231357)),
 (304, np.float64(0.12171612389003691)),
 (305, np.float64(0.04348853820356281)),
 (306, np.float64(0.0)),
 (307, np.float64(0.06984302957695783)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.0894427190999916)),
 (311, np.float64(0.0267739776300833)),
 (312, np.float64(0.0)),
 (313, np.float64(0.20952908873087345)),
 (314, np.float64(0.0267739776300833)),
 (315, np.float64(0.04095300778893008)),
 (316, np.float64(0.10336227882434039)),
 (317, np.float64(0.04901430813958719)),
 (318, np.float64(0.02387049580131443)),
 (319, np.float64(0.023570226039551584)),
 (320, np.float64(0.07071067811865475)),
 (321, np.float64(0.08791739645277159)),
 (322, np.float64(0.06666666666666667)),
 (323, np.float64(0.08888888888888889)),
 (324, np.float64(0.0417482860723433)),
 (325, np.float64(0.08432740427115677)),
 (326, np.float64(0.061429511683395124)),
 (327, np.float64(0.1147550621098494)),
 (328, np.float64(0.039840953644479794)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0439586982263858)),
 (331, np.float64(0.05923488777590924)),
 (332, np.float64(0.12091270835166862)),
 (333, np.float64(0.17284832429004493)),
 (334, np.float64(0.01698823971458752)),
 (335, np.float64(0.0219793491131929)),
 (336, np.float64(0.020672455764868078)),
 (337, np.float64(0.022473328748774737)),
 (338, np.float64(0.0)),
 (339, np.float64(0.0535479552601666)),
 (340, np.float64(0.06666666666666667)),
 (341, np.float64(0.0659380473395787)),
 (342, np.float64(0.0)),
 (343, np.float64(0.022733144649015782)),
 (344, np.float64(0.036423890980543536)),
 (345, np.float64(0.019086611143795607)),
 (346, np.float64(0.03233808333817773)),
 (347, np.float64(0.0803219328902499)),
 (348, np.float64(0.0)),
 (349, np.float64(0.08304547985373997)),
 (350, np.float64(0.02817180849095055)),
 (351, np.float64(0.036423890980543536)),
 (352, np.float64(0.09200874124564723)),
 (353, np.float64(0.0803219328902499)),
 (354, np.float64(0.09480909262799544)),
 (355, np.float64(0.02087414303617165)),
 (356, np.float64(0.08791739645277159)),
 (357, np.float64(0.04901430813958719)),
 (358, np.float64(0.0)),
 (359, np.float64(0.11694106924093724)),
 (360, np.float64(0.17038855027411945)),
 (361, np.float64(0.044946657497549475)),
 (362, np.float64(0.08606629658238706)),
 (363, np.float64(0.04020151261036849)),
 (364, np.float64(0.15214515486254615)),
 (365, np.float64(0.03091592638401122)),
 (366, np.float64(0.06584863977663931)),
 (367, np.float64(0.042591770999996)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.04323377011671169)),
 (371, np.float64(0.0439586982263858)),
 (372, np.float64(0.0)),
 (373, np.float64(0.03849001794597505)),
 (374, np.float64(0.04836508334066745)),
 (375, np.float64(0.02556549962824568)),
 (376, np.float64(0.020286020648339488)),
 (377, np.float64(0.020286020648339488)),
 (378, np.float64(0.0)),
 (379, np.float64(0.07453559924999299)),
 (380, np.float64(0.046004370622823615)),
 (381, np.float64(0.07647191129018727)),
 (382, np.float64(0.026352313834736494)),
 (383, np.float64(0.0)),
 (384, np.float64(0.021744269101781406)),
 (385, np.float64(0.0439586982263858)),
 (386, np.float64(0.03948992518393949)),
 (387, np.float64(0.04348853820356281)),
 (388, np.float64(0.0)),
 (389, np.float64(0.021744269101781406)),
 (390, np.float64(0.09428090415820634)),
 (391, np.float64(0.05270462766947299)),
 (392, np.float64(0.06984302957695783)),
 (393, np.float64(0.08973031700969426)),
 (394, np.float64(0.10540925533894598)),
 (395, np.float64(0.07071067811865475)),
 (396, np.float64(0.035634832254989916)),
 (397, np.float64(0.019407416991319402)),
 (398, np.float64(0.0596284793999944)),
 (399, np.float64(0.020100756305184243)),
 (400, np.float64(0.07829602926862712)),
 (401, np.float64(0.041344911529736156)),
 (402, np.float64(0.10143010324169743)),
 (403, np.float64(0.12091270835166862)),
 (404, np.float64(0.026352313834736494)),
 (405, np.float64(0.0490880693673816)),
 (406, np.float64(0.046562019717971886)),
 (407, np.float64(0.02868876552746235)),
 (408, np.float64(0.02923526731023431)),
 (409, np.float64(0.062017367294604234)),
 (410, np.float64(0.11846977555181847)),
 (411, np.float64(0.019744962591969745)),
 (412, np.float64(0.13176156917368248)),
 (413, np.float64(0.035892126803877704)),
 (414, np.float64(0.03312693299999688)),
 (415, np.float64(0.057735026918962574)),
 (416, np.float64(0.06467616667635546)),
 (417, np.float64(0.02556549962824568)),
 (418, np.float64(0.048507125007266595)),
 (419, np.float64(0.0)),
 (420, np.float64(0.044946657497549475)),
 (421, np.float64(0.0219793491131929)),
 (422, np.float64(0.11744404390294069)),
 (423, np.float64(0.027681826617913324)),
 (424, np.float64(0.0)),
 (425, np.float64(0.0298142396999972)),
 (426, np.float64(0.0)),
 (427, np.float64(0.045466289298031565)),
 (428, np.float64(0.11111111111111112)),
 (429, np.float64(0.04714045207910317)),
 (430, np.float64(0.039840953644479794)),
 (431, np.float64(0.07669649888473704)),
 (432, np.float64(0.08114408259335795)),
 (433, np.float64(0.056796183424706485)),
 (434, np.float64(0.0)),
 (435, np.float64(0.0879173964527716)),
 (436, np.float64(0.020286020648339488)),
 (437, np.float64(0.05822225097395821)),
 (438, np.float64(0.018349396085439344)),
 (439, np.float64(0.11501092655705904)),
 (440, np.float64(0.019086611143795607)),
 (441, np.float64(0.021744269101781406)),
 (442, np.float64(0.027681826617913324)),
 (443, np.float64(0.021744269101781406)),
 (444, np.float64(0.09960238411119948)),
 (445, np.float64(0.053074489243427524)),
 (446, np.float64(0.05590169943749475)),
 (447, np.float64(0.07352146220938079)),
 (448, np.float64(0.03948992518393949)),
 (449, np.float64(0.02923526731023431)),
 (450, np.float64(0.02087414303617165)),
 (451, np.float64(0.12253577034896797)),
 (452, np.float64(0.029095718698132322)),
 (453, np.float64(0.0563436169819011)),
 (454, np.float64(0.0)),
 (455, np.float64(0.149071198499986)),
 (456, np.float64(0.09390602830316849)),
 (457, np.float64(0.04836508334066745)),
 (458, np.float64(0.05383819020581655)),
 (459, np.float64(0.039840953644479794)),
 (460, np.float64(0.05547001962252292)),
 (461, np.float64(0.09312403943594377)),
 (462, np.float64(0.08040302522073697)),
 (463, np.float64(0.054635836470815304)),
 (464, np.float64(0.1338698881504165)),
 (465, np.float64(0.0)),
 (466, np.float64(0.048795003647426664)),
 (467, np.float64(0.10487553416094877)),
 (468, np.float64(0.08989331499509895)),
 (469, np.float64(0.0)),
 (470, np.float64(0.01957400731715678)),
 (471, np.float64(0.1297498240269205)),
 (472, np.float64(0.024507154069793594)),
 (473, np.float64(0.044444444444444446)),
 (474, np.float64(0.10183501544346313)),
 (475, np.float64(0.1126872339638022)),
 (476, np.float64(0.07491109582924912)),
 (477, np.float64(0.060858061945018464)),
 (478, np.float64(0.12712834523274563)),
 (479, np.float64(0.08664587415167273)),
 (480, np.float64(0.05489246463950789)),
 (481, np.float64(0.0267739776300833)),
 (482, np.float64(0.16609095970747995)),
 (483, np.float64(0.03091592638401122)),
 (484, np.float64(0.0)),
 (485, np.float64(0.09325048082403138)),
 (486, np.float64(0.0)),
 (487, np.float64(0.023281009858985943)),
 (488, np.float64(0.0903876907577734)),
 (489, np.float64(0.12285902336679023)),
 (490, np.float64(0.06666666666666667)),
 (491, np.float64(0.0)),
 (492, np.float64(0.1690308509457033)),
 (493, np.float64(0.03108349360801046)),
 (494, np.float64(0.2422406975624772)),
 (495, np.float64(0.08791739645277159)),
 (496, np.float64(0.019086611143795607)),
 (497, np.float64(0.10989674556596449)),
 (498, np.float64(0.08164965809277261)),
 (499, np.float64(0.024507154069793594)),
 (500, np.float64(0.11644450194791642)),
 (501, np.float64(0.04095300778893008)),
 (502, np.float64(0.019744962591969745)),
 (503, np.float64(0.0954819832052577)),
 (504, np.float64(0.0)),

In [13]:
sorted(list(enumerate(similarity_mat[0])), reverse=True, key = lambda x : x[1])[1:6] #excluding the first(itself)

[(1168, np.float64(0.24693239916239745)),
 (494, np.float64(0.2422406975624772)),
 (567, np.float64(0.2412090756622109)),
 (525, np.float64(0.23570226039551584)),
 (2223, np.float64(0.23190036174568118))]

In [14]:
def recommend(movie):
    movie_index = df[df["title"] == movie].index[0]
    movie_list_title = []
    distances = similarity_mat[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key = lambda x : x[1])[1:6] #excluding the first(itself)
    for i in movie_list:
        print(df.iloc[i[0]].title)

In [15]:
recommend("Iron Man")

Iron Man 3
Iron Man 2
Avengers: Age of Ultron
Ant-Man
Guardians of the Galaxy

In [16]:
import pickle

pickle.dump(df, open("movies.pkl","wb"))
pickle.dump(similarity_mat, open("similarity.pkl","wb"))
pickle.dump(cv, open("vectorizer.pkl","wb"))

In [17]:
df[df["title"] == "Toy Stroy"]

Empty DataFrame
Columns: [id, title, tags]
Index: []